#pragma once

#include <pluginterfaces/base/fplatform.h>

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"vstsync.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"vstsync VST3 (64Bit)"
#else
#define stringFileDescription	"vstsync VST3"
#endif
#define stringCompanyName		"My Plug-in Company\0"
#define stringLegalCopyright	"Copyright(c) 2023 My Plug-in Company."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
