#pragma once

#include <pluginterfaces/base/fplatform.h>

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "DAWSync.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "DAWSync VST3 (64Bit)"
#else
#define stringFileDescription "DAWSync VST3"
#endif
#define stringCompanyName "adrien salon\0"
#define stringLegalCopyright "Copyright(c) 2023 adrien salon."
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
